Changelog file
matchboxdesigngroup/kindling pull request #59
Opened 2024-12-19 12:59 UTC by EugeneKyale

## Changes proposed in this pull request

This PR introduces a file to document future changelog entries.

Closes (GitHub issue number or Asana task link)

## Pre-submit checklist

As the author of this pull request, I verify that:

- [ ] I have set the target branch to `master`.
- [ ] I have detailed the purpose of this Pull Request in a non-technical way.
- [ ] I have detailed how to test the changes in the Pull Request.
- [ ] I have detailed the functional tests required for approval.
- [ ] I have performed a self-review of my code to ensure it is DRY and follows the team's coding standards.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have verified that my code does not introduce a debug warning in my local environment.
- [ ] I have verified that the functional tests work in my local environment.
- [ ] I have verified that all automated tests pass or have provided a detailed comment about why I am submitting with a failed pipeline.
- [ ] I have verified that any dependent changes have been merged and published in downstream commits.
- [ ] I have added a link to this Pull Request in the Asana task.
- [ ] I have moved the Asana task to "Ready for Functional Review".
- [ ] I have left a comment in Asana and GitHub tagging a team member with a request for `review.

## Testing

### How to test the changes in this pull request

Follow the steps below to test the changes in this PR.

1. Deploy this branch to the `dev` environment.
2. Navigate to...
3. 

### Functional tests

As the functional tester for this pull request, I verify that:

- [ ] It [does something]
- [ ] it does not...
- [ ] As an admin, I can...
- [ ] As a user, I can...

Once testing is complete, notify the author of any failed tests and move the task to "Kick back" in Asana. If all tests pass, move the task to "Ready for Code Review" in Asana and tag a team member for code review.

### Code review

As the code reviewer for this pull request, I verify that:

- [ ] All automated tests have passed.
- [ ] The code is written (or documented) in a way that is easy to understand.
- [ ] The code is free of obvious errors.
- [ ] The code is free of obvious duplication.
- [ ] The code follows our coding standards.
- [ ] The code is sanitized or escaped appropriately for any SQL or XSS injection possibilities.

Once testing is complete, notify the author of any failed tests and move the task to "Kick back" in Asana or continue with the "merging" steps below.

## Merging

As the individual merging this pull request, I verify that:

- [ ] All automated tests have passed.
- [ ] All functional tests have passed.
- [ ] All code review tests have passed.
- [ ] I have moved the task to "Ready to Deploy" in Asana and notified the pull request author.

2025-07-11 14:46 UTC, EugeneKyale commented
@unscripted @sstruemph The change log file has been updated to match the https://common-changelog.org/ standard as discussed. Please review it before we adapt it to the other projects.

2025-07-16 00:16 UTC, unscripted requested changes
Once the two meta items are updated, this is good to merge.

2025-07-16 00:16 UTC, unscripted commented on CHANGELOG.md
> +**Requires at least:** 6.0
We need to change this to 6.6 due to support for Section Styles.

2025-07-16 00:16 UTC, unscripted commented on CHANGELOG.md
> +**Tested up to:** 6.3
We're tested up to 6.8.2

2025-07-16 10:30 UTC, EugeneKyale commented
> Once the two meta items are updated, this is good to merge.

@unscripted I've made the recommended changes.

2025-07-16 10:30 UTC, merged